Link to RPM Fusion package for Fedora.
Moonbase59/loudgain pull request #43
Opened 2021-01-15 13:22 UTC by mavit

2022-04-10 11:16 UTC, joonas-fi commented
Thanks for this advice!

I successfully produced a Dockerfile that can be used to build a Docker image:
```dockerfile
FROM fedora:latest

WORKDIR /workspace

ENTRYPOINT ["/usr/bin/loudgain"]

RUN rpm -q rpmfusion-free-release || sudo yum install --assumeyes https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-`rpm -E %fedora`.noarch.rpm \
	&& sudo yum install --assumeyes loudgain
```

2023-03-12 16:37 UTC, Conan-Kudo requested changes

2023-03-12 16:37 UTC, Conan-Kudo commented on README.md
> +yum swap --allowerasing ffmpeg-free ffmpeg
Instead recommend installing `libavcodec-freeworld` to overlay the extra codecs.

2023-03-19 15:44 UTC, mavit commented on README.md
> +yum swap --allowerasing ffmpeg-free ffmpeg
Thanks for the tip.  Actually, these days I don't think RPM Fusion adds any useful audio codecs, so I'm going to drop the suggestion entirely.

2025-08-02 11:19 UTC, mavit commented
`loudgain` was replaced in Fedora by `rsgain`, so this is no-longer relevant.

2025-08-02 11:19 UTC, closed without merging